version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true