// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AltergoAPI.Nss.Core.Models;
//
//    var domainsResult = DomainsResult.FromJson(jsonString);

namespace AltergoAPI.Nss.Core.Models
{
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class DomainsResult
    {
        public static List<string> FromJson(string json) => JsonConvert.DeserializeObject<List<string>>(json, ConverterDomains.Settings);
    }

    public static class SerializeDomainsResult
    {
        public static string ToJson(this List<string> self) => JsonConvert.SerializeObject(self, ConverterDomains.Settings);
    }

    internal static class ConverterDomains
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
