#nullable enable
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AltergoAPI.Nss.Core.Models;
//
//    var nssResults = NssResults.FromJson(jsonString);

using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AltergoAPI.Nss.Core.Models
{
    public partial class NssResults
    {
        [JsonProperty("descripcion")]
        public object? Descripcion { get; set; }

        [JsonProperty("persona", NullValueHandling = NullValueHandling.Ignore)]
        public Persona? Persona { get; set; }
    }

    public class Persona
    {
        [JsonProperty("curp", NullValueHandling = NullValueHandling.Ignore)]
        public string? Curp { get; set; }

        [JsonProperty("nombre", NullValueHandling = NullValueHandling.Ignore)]
        public string? Nombre { get; set; }

        [JsonProperty("primerApellido", NullValueHandling = NullValueHandling.Ignore)]
        public string? PrimerApellido { get; set; }

        [JsonProperty("segundoApellido", NullValueHandling = NullValueHandling.Ignore)]
        public string? SegundoApellido { get; set; }

        [JsonProperty("fechaNacimiento", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? FechaNacimiento { get; set; }

        [JsonProperty("sexo", NullValueHandling = NullValueHandling.Ignore)]
        public string? Sexo { get; set; }

        [JsonProperty("nss", NullValueHandling = NullValueHandling.Ignore)]
        public string? Nss { get; set; }

        //[JsonProperty("idAsignacionNss", NullValueHandling = NullValueHandling.Ignore)]
        //public long? IdAsignacionNss { get; set; }

        //[JsonProperty("correo", NullValueHandling = NullValueHandling.Ignore)]
        //public string Correo { get; set; }

        public string? EntidadNacimiento { get; set; }

        public int? EdadCumplida { get; set; }
    }

    public partial class NssResults
    {
        public static NssResults FromJson(string json) => JsonConvert.DeserializeObject<NssResults>(json, NsConverter.Settings);
    }

    public static class NsSerialize
    {
        public static string ToJson(this NssResults self) => JsonConvert.SerializeObject(self, NsConverter.Settings);
    }

    internal static class NsConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
#nullable disable