// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AltergoAPI.Nss.Core.Models;
//
//    var ocrResult = OcrResult.FromJson(jsonString);

namespace AltergoAPI.Nss.Core.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OcrResult
    {
        [JsonProperty("analyzeResult", NullValueHandling = NullValueHandling.Ignore)]
        public AnalyzeResult AnalyzeResult { get; set; }

        [JsonProperty("createdDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedDateTime { get; set; }

        [JsonProperty("lastUpdatedDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public string LastUpdatedDateTime { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class AnalyzeResult
    {
        [JsonProperty("documentResults", NullValueHandling = NullValueHandling.Ignore)]
        public List<DocumentResult> DocumentResults { get; set; }

        [JsonProperty("errors", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Errors { get; set; }

        [JsonProperty("pageResults", NullValueHandling = NullValueHandling.Ignore)]
        public List<PageResult> PageResults { get; set; }

        [JsonProperty("readResults", NullValueHandling = NullValueHandling.Ignore)]
        public List<ReadResult> ReadResults { get; set; }

        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }
    }

    public partial class DocumentResult
    {
        [JsonProperty("docType", NullValueHandling = NullValueHandling.Ignore)]
        public string DocType { get; set; }

        [JsonProperty("docTypeConfidence", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? DocTypeConfidence { get; set; }

        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public Fields Fields { get; set; }

        [JsonProperty("modelId", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? ModelId { get; set; }

        [JsonProperty("pageRange", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> PageRange { get; set; }
    }

    public partial class Fields
    {
        [JsonProperty("APATERNO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Apaterno { get; set; }

        [JsonProperty("AMATERNO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Amaterno { get; set; }

        [JsonProperty("NOMBRES", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Nombres { get; set; }

        [JsonProperty("DOMICILIO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Domicilio { get; set; }

        [JsonProperty("CLAVELECTOR", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Clavelector { get; set; }

        [JsonProperty("CURP", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Curp { get; set; }

        [JsonProperty("FNACIMIENTO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Fnacimiento { get; set; }

        [JsonProperty("SECCION", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Seccion { get; set; }

        //[JsonProperty("MRZT", NullValueHandling = NullValueHandling.Ignore)]
        //public CampoOcr Mrz { get; set; }

        [JsonProperty("GENERO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Genero { get; set; }

        [JsonProperty("AREGISTRO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr AnioRegistro { get; set; }

        [JsonProperty("VIGENCIA", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Vigencia { get; set; }

        [JsonProperty("MUNICIPIO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Municipio { get; set; }

        [JsonProperty("ESTADO", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Estado { get; set; }

        [JsonProperty("LOCALIDAD", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Localidad { get; set; }

        [JsonProperty("EMISION", NullValueHandling = NullValueHandling.Ignore)]
        public CampoOcr Emision { get; set; }
    }

    public partial class CampoOcr
    {
        [JsonProperty("boundingBox", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> BoundingBox { get; set; }

        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? Confidence { get; set; }

        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public long? Page { get; set; }

        [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
        public string Text { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("valueString", NullValueHandling = NullValueHandling.Ignore)]
        public string ValueString { get; set; }

        [JsonProperty("valueDate", NullValueHandling = NullValueHandling.Ignore)]
        public string ValueDate { get; set; }
    }

    public partial class PageResult
    {
        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public long? Page { get; set; }

        [JsonProperty("tables", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Tables { get; set; }
    }

    public partial class ReadResult
    {
        [JsonProperty("angle", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? Angle { get; set; }

        [JsonProperty("height", NullValueHandling = NullValueHandling.Ignore)]
        public long? Height { get; set; }

        [JsonProperty("page", NullValueHandling = NullValueHandling.Ignore)]
        public long? Page { get; set; }

        [JsonProperty("selectionMarks", NullValueHandling = NullValueHandling.Ignore)]
        public List<SelectionMark> SelectionMarks { get; set; }

        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore)]
        public string Unit { get; set; }

        [JsonProperty("width", NullValueHandling = NullValueHandling.Ignore)]
        public long? Width { get; set; }
    }

    public partial class SelectionMark
    {
        [JsonProperty("boundingBox", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> BoundingBox { get; set; }

        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public decimal? Confidence { get; set; }

        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; set; }
    }

    public partial class OcrResult
    {
        public static OcrResult FromJson(string json) => JsonConvert.DeserializeObject<OcrResult>(json, AltergoAPI.Nss.Core.Models.ConverterOcrResult.Settings);
    }

    public static class SerializeOcrResult
    {
        public static string ToJson(this OcrResult self) => JsonConvert.SerializeObject(self, AltergoAPI.Nss.Core.Models.ConverterOcrResult.Settings);
    }

    internal static class ConverterOcrResult
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
