// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AltergoAPI.Nss.Core.Models;
//
//    var umResults = UmResults.FromJson(jsonString);

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace AltergoAPI.Nss.Core.Models
{
    public partial class UmResults
    {
        [JsonProperty("clave", NullValueHandling = NullValueHandling.Ignore)]
        public long? Clave { get; set; }

        [JsonProperty("domicilio", NullValueHandling = NullValueHandling.Ignore)]
        public string Domicilio { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("nombre", NullValueHandling = NullValueHandling.Ignore)]
        public string Nombre { get; set; }

        [JsonProperty("telefono", NullValueHandling = NullValueHandling.Ignore)]
        public string Telefono { get; set; }

        [JsonProperty("tipo", NullValueHandling = NullValueHandling.Ignore)]
        public string Tipo { get; set; }

        [JsonProperty("latitud", NullValueHandling = NullValueHandling.Ignore)]
        public string Latitud { get; set; }

        [JsonProperty("longitud", NullValueHandling = NullValueHandling.Ignore)]
        public string Longitud { get; set; }
    }

    public partial class UmResults
    {
        public static UmResults FromJson(string json) => JsonConvert.DeserializeObject<UmResults>(json, UmConverter.Settings);
    }

    public static class UmSerialize
    {
        public static string ToJson(this UmResults self) => JsonConvert.SerializeObject(self, UmConverter.Settings);
    }

    internal static class UmConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
