name: Construir y Desplegar en Azure

env:
  AZURE_WEBAPP_NAME: 'bbva-back'
  AZURE_WEBAPP_PACKAGE_PATH: 'Backend/ValidadorDatos'
  DOTNET_VERSION: '6'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restaurar paquetes
        run: dotnet restore ValidadorDatos.sln

      - name: Compilar
        run: dotnet build ValidadorDatos.sln --configuration Release

      - name: Publicar artefacto
        run: dotnet publish ValidadorDatos.sln -c Release -o ${{env.DOTNET_ROOT}}/validador

      - name: Subir artefacto para desplegar
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/validador

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Desplegar en Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
