name: Backend Validador de Datos

env:
  AZURE_WEBAPP_NAME: 'bbva-back'
  AZURE_WEBAPP_PACKAGE_PATH: 'Backend/ValidadorDatos'
  TERRAFORM_PACKAGE_PATH: 'Infraestructura/Web'
  DOTNET_VERSION: '6'

on:
  push:
    branches: [ "master" ]

jobs:
  construir:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restaurar paquetes
        run: dotnet restore ValidadorDatos.sln

      - name: Compilar
        run: dotnet build ValidadorDatos.sln --configuration Release

      - name: Publicar artefacto
        run: dotnet publish ValidadorDatos.sln -c Release -o ${{env.DOTNET_ROOT}}/validador

      - name: Subir artefacto para desplegar
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/validador
  
  terraformar:
    runs-on: ubuntu-latest
    environment: production
    needs: construir
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PACKAGE_PATH }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: 'Sesion en Azure'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: 'Comandos Az'
        run: |
          az account show
          az group list
          pwd
  
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init --backend=true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

  desplegar:
    runs-on: ubuntu-latest
    needs: [construir, terraformar]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Desplegar en Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
